### ISSUE TITLE
Problem making rgpm: Makefile:27: recipe for target 'SuperEmbedding.o' failed

### ISSUE THREAD

**Issue by rmurphy2718** [dccspeed/rgpm#1]
Dear RGPM,

I am having trouble with running `make`

Here is my log:

[rgpm_log_1.log](https://github.com/dccspeed/rgpm/files/3612992/rgpm_log_1.log)

Here is information on my installed libraries and g++

> (base) rgpm $ apt-cache policy libboost-all-dev
> libboost-all-dev:
>   Installed: 1.58.0.1ubuntu1
>   Candidate: 1.58.0.1ubuntu1
>   Version table:
>  *** 1.58.0.1ubuntu1 500
>         500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
>         100 /var/lib/dpkg/status

(I think the crossouts below are due to the "~" character
> apt-cache policy libtbb-dev
>   Installed: 4.4~20151115-0ubuntu3
>   Candidate: 4.4~20151115-0ubuntu3
>   Version table:
>  *** 4.4~20151115-0ubuntu3 500
>         500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
>         100 /var/lib/dpkg/status

> (base) rgpm $ apt-cache policy libgsl-dev
> libgsl-dev:
>   Installed: 2.1+dfsg-2
>   Candidate: 2.1+dfsg-2
>   Version table:
>  *** 2.1+dfsg-2 500
>         500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
>         100 /var/lib/dpkg/status

> (base) rgpm $ apt-cache policy libsparsehash-dev
> libsparsehash-dev:
>   Installed: 2.0.2-1
>   Candidate: 2.0.2-1
>   Version table:
>  *** 2.0.2-1 500
>         500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
>         500 http://us.archive.ubuntu.com/ubuntu xenial/universe i386 Packages
>         100 /var/lib/dpkg/status

C++ compiler

> (base) rgpm $ g++ --version
> g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Please help.  Thanks!

**Comment by carloshct** [comment]
Fixed. I added the missing file.
Thanks
