### ISSUE TITLE
EmbeddingUtils.cpp:96:19: error: variable-sized object may not be initialized       int adjsize[s]={0};

### ISSUE THREAD

**Issue by yangzez** [dccspeed/rgpm#2]
Dear RGPM,

I am having trouble with running make

Here is my log:

[makelog.log](https://github.com/dccspeed/rgpm/files/3613192/makelog.log)

Here is information on my installed libraries and g++

> ChouYangzedeMacBook-Pro:rgpm-master ZachChou$ brew info boost
> boost: stable 1.71.0 (bottled), HEAD
> Collection of portable C++ source libraries
> https://www.boost.org/
> /usr/local/Cellar/boost/1.71.0 (14,377 files, 522.8MB) *
>   Poured from bottle on 2019-09-14 at 17:52:18
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb
> ==> Dependencies
> Required: icu4c ✔
> ==> Options
> --HEAD
> 	Install HEAD version
> ==> Analytics
> install: 48,341 (30 days), 126,190 (90 days), 645,637 (365 days)
> install_on_request: 16,773 (30 days), 44,189 (90 days), 205,778 (365 days)
> build_error: 0 (30 days)

> ChouYangzedeMacBook-Pro:rgpm-master ZachChou$ brew info gsl
> gsl: stable 2.6 (bottled)
> Numerical library for C and C++
> https://www.gnu.org/software/gsl/
> /usr/local/Cellar/gsl/2.6 (289 files, 9.8MB) *
>   Poured from bottle on 2019-09-14 at 17:51:02
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gsl.rb
> ==> Analytics
> install: 7,359 (30 days), 13,316 (90 days), 61,865 (365 days)
> install_on_request: 2,821 (30 days), 5,897 (90 days), 19,974 (365 days)
> build_error: 0 (30 days)

> ChouYangzedeMacBook-Pro:rgpm-master ZachChou$ brew info tbb
> tbb: stable 2019_U8 (bottled)
> Rich and complete approach to parallelism in C++
> https://www.threadingbuildingblocks.org/
> /usr/local/Cellar/tbb/2019_U8 (138 files, 2.8MB) *
>   Poured from bottle on 2019-09-14 at 17:54:43
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tbb.rb
> ==> Dependencies
> Build: cmake ✘, swig ✘
> Required: python ✔
> ==> Analytics
> install: 12,293 (30 days), 45,931 (90 days), 236,427 (365 days)
> install_on_request: 1,807 (30 days), 7,217 (90 days), 35,362 (365 days)
> build_error: 0 (30 days)

> ChouYangzedeMacBook-Pro:rgpm-master ZachChou$ brew info google-sparsehash
> google-sparsehash: stable 2.0.3 (bottled)
> Extremely memory-efficient hash_map implementation
> https://github.com/sparsehash/sparsehash
> /usr/local/Cellar/google-sparsehash/2.0.3 (49 files, 607.5KB) *
>   Poured from bottle on 2019-09-14 at 18:00:13
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/google-sparsehash.rb
> ==> Analytics
> install: 199 (30 days), 657 (90 days), 3,078 (365 days)
> install_on_request: 69 (30 days), 208 (90 days), 929 (365 days)
> build_error: 0 (30 days)

C++ compiler

> ChouYangzedeMacBook-Pro:rgpm-master ZachChou$ g++ --version
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
> Apple LLVM version 10.0.1 (clang-1001.0.46.4)
> Target: x86_64-apple-darwin18.6.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Please help. Thanks!

**Comment by carloshct** [comment]
Please, double check your gcc compiler version. I use the 5.4. 
It seems that you are using 4.2.1.
